// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: koinos/chain/object_spaces.proto

package chain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemSpaceId int32

const (
	SystemSpaceId_metadata             SystemSpaceId = 0
	SystemSpaceId_system_call_dispatch SystemSpaceId = 1
	SystemSpaceId_contract_bytecode    SystemSpaceId = 2
	SystemSpaceId_contract_metadata    SystemSpaceId = 3
	SystemSpaceId_transaction_nonce    SystemSpaceId = 4
)

// Enum value maps for SystemSpaceId.
var (
	SystemSpaceId_name = map[int32]string{
		0: "metadata",
		1: "system_call_dispatch",
		2: "contract_bytecode",
		3: "contract_metadata",
		4: "transaction_nonce",
	}
	SystemSpaceId_value = map[string]int32{
		"metadata":             0,
		"system_call_dispatch": 1,
		"contract_bytecode":    2,
		"contract_metadata":    3,
		"transaction_nonce":    4,
	}
)

func (x SystemSpaceId) Enum() *SystemSpaceId {
	p := new(SystemSpaceId)
	*p = x
	return p
}

func (x SystemSpaceId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemSpaceId) Descriptor() protoreflect.EnumDescriptor {
	return file_koinos_chain_object_spaces_proto_enumTypes[0].Descriptor()
}

func (SystemSpaceId) Type() protoreflect.EnumType {
	return &file_koinos_chain_object_spaces_proto_enumTypes[0]
}

func (x SystemSpaceId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemSpaceId.Descriptor instead.
func (SystemSpaceId) EnumDescriptor() ([]byte, []int) {
	return file_koinos_chain_object_spaces_proto_rawDescGZIP(), []int{0}
}

var File_koinos_chain_object_spaces_proto protoreflect.FileDescriptor

var file_koinos_chain_object_spaces_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2a, 0x7e, 0x0a, 0x0f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x10,
	0x00, 0x12, 0x18, 0x0a, 0x14, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x10, 0x04,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73,
	0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_koinos_chain_object_spaces_proto_rawDescOnce sync.Once
	file_koinos_chain_object_spaces_proto_rawDescData = file_koinos_chain_object_spaces_proto_rawDesc
)

func file_koinos_chain_object_spaces_proto_rawDescGZIP() []byte {
	file_koinos_chain_object_spaces_proto_rawDescOnce.Do(func() {
		file_koinos_chain_object_spaces_proto_rawDescData = protoimpl.X.CompressGZIP(file_koinos_chain_object_spaces_proto_rawDescData)
	})
	return file_koinos_chain_object_spaces_proto_rawDescData
}

var file_koinos_chain_object_spaces_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_koinos_chain_object_spaces_proto_goTypes = []interface{}{
	(SystemSpaceId)(0), // 0: koinos.chain.system_space_id
}
var file_koinos_chain_object_spaces_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_koinos_chain_object_spaces_proto_init() }
func file_koinos_chain_object_spaces_proto_init() {
	if File_koinos_chain_object_spaces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_koinos_chain_object_spaces_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_koinos_chain_object_spaces_proto_goTypes,
		DependencyIndexes: file_koinos_chain_object_spaces_proto_depIdxs,
		EnumInfos:         file_koinos_chain_object_spaces_proto_enumTypes,
	}.Build()
	File_koinos_chain_object_spaces_proto = out.File
	file_koinos_chain_object_spaces_proto_rawDesc = nil
	file_koinos_chain_object_spaces_proto_goTypes = nil
	file_koinos_chain_object_spaces_proto_depIdxs = nil
}
