// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: koinos/contracts/pob/pob.proto

package pob

import (
	_ "github.com/koinos/koinos-proto-golang/koinos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKeyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *PublicKeyRecord) Reset() {
	*x = PublicKeyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyRecord) ProtoMessage() {}

func (x *PublicKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyRecord.ProtoReflect.Descriptor instead.
func (*PublicKeyRecord) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyRecord) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed                []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Difficulty          []byte `protobuf:"bytes,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	LastBlockTime       uint64 `protobuf:"varint,3,opt,name=last_block_time,json=lastBlockTime,proto3" json:"last_block_time,omitempty"`
	TargetBlockInterval uint64 `protobuf:"varint,4,opt,name=target_block_interval,json=targetBlockInterval,proto3" json:"target_block_interval,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *Metadata) GetDifficulty() []byte {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *Metadata) GetLastBlockTime() uint64 {
	if x != nil {
		return x.LastBlockTime
	}
	return 0
}

func (x *Metadata) GetTargetBlockInterval() uint64 {
	if x != nil {
		return x.TargetBlockInterval
	}
	return 0
}

type SignatureData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfProof  []byte `protobuf:"bytes,1,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
	VrfHash   []byte `protobuf:"bytes,2,opt,name=vrf_hash,json=vrfHash,proto3" json:"vrf_hash,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignatureData) Reset() {
	*x = SignatureData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureData) ProtoMessage() {}

func (x *SignatureData) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureData.ProtoReflect.Descriptor instead.
func (*SignatureData) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{2}
}

func (x *SignatureData) GetVrfProof() []byte {
	if x != nil {
		return x.VrfProof
	}
	return nil
}

func (x *SignatureData) GetVrfHash() []byte {
	if x != nil {
		return x.VrfHash
	}
	return nil
}

func (x *SignatureData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VrfPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed      []byte `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	BlockTime uint64 `protobuf:"varint,2,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
}

func (x *VrfPayload) Reset() {
	*x = VrfPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfPayload) ProtoMessage() {}

func (x *VrfPayload) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfPayload.ProtoReflect.Descriptor instead.
func (*VrfPayload) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{3}
}

func (x *VrfPayload) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *VrfPayload) GetBlockTime() uint64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

type RegisterPublicKeyArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *RegisterPublicKeyArguments) Reset() {
	*x = RegisterPublicKeyArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPublicKeyArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyArguments) ProtoMessage() {}

func (x *RegisterPublicKeyArguments) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyArguments.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyArguments) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterPublicKeyArguments) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RegisterPublicKeyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterPublicKeyResult) Reset() {
	*x = RegisterPublicKeyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPublicKeyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyResult) ProtoMessage() {}

func (x *RegisterPublicKeyResult) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyResult.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyResult) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{5}
}

type BurnArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAmount uint64 `protobuf:"varint,1,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	BurnAddress []byte `protobuf:"bytes,2,opt,name=burn_address,json=burnAddress,proto3" json:"burn_address,omitempty"`
	VhpAddress  []byte `protobuf:"bytes,3,opt,name=vhp_address,json=vhpAddress,proto3" json:"vhp_address,omitempty"`
}

func (x *BurnArguments) Reset() {
	*x = BurnArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BurnArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnArguments) ProtoMessage() {}

func (x *BurnArguments) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnArguments.ProtoReflect.Descriptor instead.
func (*BurnArguments) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{6}
}

func (x *BurnArguments) GetTokenAmount() uint64 {
	if x != nil {
		return x.TokenAmount
	}
	return 0
}

func (x *BurnArguments) GetBurnAddress() []byte {
	if x != nil {
		return x.BurnAddress
	}
	return nil
}

func (x *BurnArguments) GetVhpAddress() []byte {
	if x != nil {
		return x.VhpAddress
	}
	return nil
}

type BurnResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BurnResult) Reset() {
	*x = BurnResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BurnResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnResult) ProtoMessage() {}

func (x *BurnResult) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnResult.ProtoReflect.Descriptor instead.
func (*BurnResult) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{7}
}

type GetMetadataArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMetadataArguments) Reset() {
	*x = GetMetadataArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetadataArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataArguments) ProtoMessage() {}

func (x *GetMetadataArguments) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataArguments.ProtoReflect.Descriptor instead.
func (*GetMetadataArguments) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{8}
}

type GetMetadataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Metadata `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetMetadataResult) Reset() {
	*x = GetMetadataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetadataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResult) ProtoMessage() {}

func (x *GetMetadataResult) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResult.ProtoReflect.Descriptor instead.
func (*GetMetadataResult) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{9}
}

func (x *GetMetadataResult) GetValue() *Metadata {
	if x != nil {
		return x.Value
	}
	return nil
}

type RegisterPublicKeyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address   []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RegisterPublicKeyEvent) Reset() {
	*x = RegisterPublicKeyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_pob_pob_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPublicKeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyEvent) ProtoMessage() {}

func (x *RegisterPublicKeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_pob_pob_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyEvent.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyEvent) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_pob_pob_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterPublicKeyEvent) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterPublicKeyEvent) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_koinos_contracts_pob_pob_proto protoreflect.FileDescriptor

var file_koinos_contracts_pob_pob_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x70, 0x6f, 0x62, 0x2f, 0x70, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x70, 0x6f, 0x62, 0x1a, 0x14, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x11,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x23, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x00, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0xae, 0x01, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x00, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x24, 0x0a,
	0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01,
	0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x36, 0x0a, 0x15, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02,
	0x30, 0x01, 0x52, 0x13, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x78, 0x0a, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x09, 0x76, 0x72, 0x66,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x04, 0x80, 0xb5,
	0x18, 0x00, 0x52, 0x08, 0x76, 0x72, 0x66, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1f, 0x0a, 0x08,
	0x76, 0x72, 0x66, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x04,
	0x80, 0xb5, 0x18, 0x00, 0x52, 0x07, 0x76, 0x72, 0x66, 0x48, 0x61, 0x73, 0x68, 0x12, 0x22, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x42, 0x04, 0x80, 0xb5, 0x18, 0x00, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x4a, 0x0a, 0x0b, 0x76, 0x72, 0x66, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x18, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x04,
	0x80, 0xb5, 0x18, 0x00, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0a, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02,
	0x30, 0x01, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x44, 0x0a,
	0x1d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x23,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x00, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x87, 0x01, 0x0a, 0x0e, 0x62, 0x75, 0x72, 0x6e, 0x5f, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x0b,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0c, 0x62,
	0x75, 0x72, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x06, 0x52, 0x0b, 0x62, 0x75, 0x72, 0x6e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0b, 0x76, 0x68, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x06, 0x52,
	0x0a, 0x76, 0x68, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x62,
	0x75, 0x72, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x67, 0x65,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x6f, 0x69,
	0x6e, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x6f,
	0x62, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x60, 0x0a, 0x19, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x00, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x42, 0x04, 0x80, 0xb5, 0x18, 0x06, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x6f, 0x69,
	0x6e, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x6f,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_koinos_contracts_pob_pob_proto_rawDescOnce sync.Once
	file_koinos_contracts_pob_pob_proto_rawDescData = file_koinos_contracts_pob_pob_proto_rawDesc
)

func file_koinos_contracts_pob_pob_proto_rawDescGZIP() []byte {
	file_koinos_contracts_pob_pob_proto_rawDescOnce.Do(func() {
		file_koinos_contracts_pob_pob_proto_rawDescData = protoimpl.X.CompressGZIP(file_koinos_contracts_pob_pob_proto_rawDescData)
	})
	return file_koinos_contracts_pob_pob_proto_rawDescData
}

var file_koinos_contracts_pob_pob_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_koinos_contracts_pob_pob_proto_goTypes = []interface{}{
	(*PublicKeyRecord)(nil),            // 0: koinos.contracts.pob.public_key_record
	(*Metadata)(nil),                   // 1: koinos.contracts.pob.metadata
	(*SignatureData)(nil),              // 2: koinos.contracts.pob.signature_data
	(*VrfPayload)(nil),                 // 3: koinos.contracts.pob.vrf_payload
	(*RegisterPublicKeyArguments)(nil), // 4: koinos.contracts.pob.register_public_key_arguments
	(*RegisterPublicKeyResult)(nil),    // 5: koinos.contracts.pob.register_public_key_result
	(*BurnArguments)(nil),              // 6: koinos.contracts.pob.burn_arguments
	(*BurnResult)(nil),                 // 7: koinos.contracts.pob.burn_result
	(*GetMetadataArguments)(nil),       // 8: koinos.contracts.pob.get_metadata_arguments
	(*GetMetadataResult)(nil),          // 9: koinos.contracts.pob.get_metadata_result
	(*RegisterPublicKeyEvent)(nil),     // 10: koinos.contracts.pob.register_public_key_event
}
var file_koinos_contracts_pob_pob_proto_depIdxs = []int32{
	1, // 0: koinos.contracts.pob.get_metadata_result.value:type_name -> koinos.contracts.pob.metadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_koinos_contracts_pob_pob_proto_init() }
func file_koinos_contracts_pob_pob_proto_init() {
	if File_koinos_contracts_pob_pob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_koinos_contracts_pob_pob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKeyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignatureData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPublicKeyArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPublicKeyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BurnArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BurnResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetadataArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetadataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koinos_contracts_pob_pob_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPublicKeyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_koinos_contracts_pob_pob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_koinos_contracts_pob_pob_proto_goTypes,
		DependencyIndexes: file_koinos_contracts_pob_pob_proto_depIdxs,
		MessageInfos:      file_koinos_contracts_pob_pob_proto_msgTypes,
	}.Build()
	File_koinos_contracts_pob_pob_proto = out.File
	file_koinos_contracts_pob_pob_proto_rawDesc = nil
	file_koinos_contracts_pob_pob_proto_goTypes = nil
	file_koinos_contracts_pob_pob_proto_depIdxs = nil
}
