language: go

go:
  - 1.18.x

addons:
  apt:
    update: true
    packages:
      - ruby

jobs:
  include:
    - os: linux
      dist: jammy

install:
  - sudo gem install coveralls-lcov
  - go install github.com/jandelgado/gcov2lcov@latest
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
  - go get ./...

script:
  - go test -v github.com/koinos/koinos-proto-golang/v2/koinos/canonical -coverprofile=canonical.out -coverpkg=./koinos/canonical
  - golangci-lint run ./...

after_success:
  - gcov2lcov -infile=canonical.out -outfile=canonical.info
  - coveralls-lcov --repo-token "$COVERALLS_REPO_TOKEN" --service-name travis-pro canonical.info

notifications:
  slack:
    secure: t3PWiafiGOlcVub7v2EhP5WOHKNI6BEnw+WDeOBc+vmGEvBiXtVmNd0pR0bkNPQo+hLj2qjjxcwRYeN5OnbDVHs3nO/c3mlUdiqlnYYFCjtX6TYeOkOKZGSDAoMRgzovzQsY3fBU22Gh4V+0eZUXDeyxlc/ZgNHmOkjGHwAHL9mvGDxfMUlmr9WhHHqd4q82JVm1Oo2OWYag4FEBtkOs93cCym89CaXIiQJDb5ddhcPFBk/H9C6WJyMts8UASXiEqdP8o7rNVo+JQkK9MrXhUyXVKvOTaeJM17Z+glAH4OZpghZ66kAuxwYvtxIWIOpQ2OJdMqoZWpNtcnT+3xPtpwHV8LhLljPdIP2+IMxRGM8xH5bOOHg9AfwHKewTZDtmOx5JO3OKnV931ft/7HhdGG/cIXtBDxYFG+yTWQk1n6iHW5D/W945lyxXtBAgvDnf83/SR2WrK0t8TTAKAnBcLI0Ad0wpWOAHV9gzkNLYMgjIHTuOY0fyMRtIS+XuWoR1G2OeU46g3lyNAlrkbxIEc1jdlejqo42Ql/H8Qoqs25vWTfyTEZhxI9+6ANlKopnWjloNcE9a9hcqmQAjvCNR3Q+xXE9ygbShWYpFJFgKJZxEAtGxjHOL4O9cUONg8tsAekZaV/gquVRtiRCaC1sr1rNV4K9F5hTSdcyom9IkzXs=
    on_success: never
