// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: koinos/contracts/koin/koin.proto

package koin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManaBalanceObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance        uint64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Mana           uint64 `protobuf:"varint,2,opt,name=mana,proto3" json:"mana,omitempty"`
	LastManaUpdate uint64 `protobuf:"varint,3,opt,name=last_mana_update,json=lastManaUpdate,proto3" json:"last_mana_update,omitempty"`
}

func (x *ManaBalanceObject) Reset() {
	*x = ManaBalanceObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koinos_contracts_koin_koin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManaBalanceObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManaBalanceObject) ProtoMessage() {}

func (x *ManaBalanceObject) ProtoReflect() protoreflect.Message {
	mi := &file_koinos_contracts_koin_koin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManaBalanceObject.ProtoReflect.Descriptor instead.
func (*ManaBalanceObject) Descriptor() ([]byte, []int) {
	return file_koinos_contracts_koin_koin_proto_rawDescGZIP(), []int{0}
}

func (x *ManaBalanceObject) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ManaBalanceObject) GetMana() uint64 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *ManaBalanceObject) GetLastManaUpdate() uint64 {
	if x != nil {
		return x.LastManaUpdate
	}
	return 0
}

var File_koinos_contracts_koin_koin_proto protoreflect.FileDescriptor

var file_koinos_contracts_koin_koin_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2e, 0x6b, 0x6f, 0x69, 0x6e, 0x22, 0x79, 0x0a, 0x13, 0x6d, 0x61, 0x6e,
	0x61, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x1c, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01,
	0x52, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x12, 0x2c, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x42, 0x02, 0x30, 0x01, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x6b, 0x6f, 0x69, 0x6e, 0x6f, 0x73,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x6f,
	0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x6b,
	0x6f, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_koinos_contracts_koin_koin_proto_rawDescOnce sync.Once
	file_koinos_contracts_koin_koin_proto_rawDescData = file_koinos_contracts_koin_koin_proto_rawDesc
)

func file_koinos_contracts_koin_koin_proto_rawDescGZIP() []byte {
	file_koinos_contracts_koin_koin_proto_rawDescOnce.Do(func() {
		file_koinos_contracts_koin_koin_proto_rawDescData = protoimpl.X.CompressGZIP(file_koinos_contracts_koin_koin_proto_rawDescData)
	})
	return file_koinos_contracts_koin_koin_proto_rawDescData
}

var file_koinos_contracts_koin_koin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_koinos_contracts_koin_koin_proto_goTypes = []interface{}{
	(*ManaBalanceObject)(nil), // 0: koinos.contracts.koin.mana_balance_object
}
var file_koinos_contracts_koin_koin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_koinos_contracts_koin_koin_proto_init() }
func file_koinos_contracts_koin_koin_proto_init() {
	if File_koinos_contracts_koin_koin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_koinos_contracts_koin_koin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManaBalanceObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_koinos_contracts_koin_koin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_koinos_contracts_koin_koin_proto_goTypes,
		DependencyIndexes: file_koinos_contracts_koin_koin_proto_depIdxs,
		MessageInfos:      file_koinos_contracts_koin_koin_proto_msgTypes,
	}.Build()
	File_koinos_contracts_koin_koin_proto = out.File
	file_koinos_contracts_koin_koin_proto_rawDesc = nil
	file_koinos_contracts_koin_koin_proto_goTypes = nil
	file_koinos_contracts_koin_koin_proto_depIdxs = nil
}
